ktor:
    application:
        modules:
            - com.moashraf.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://0.0.0.0:8080/"
  audience: "client"
  issuer: "https://0.0.0.0:8080/"
  realm: "ktor-moashrafff"
  claimField: "id"

database:
  url: "jdbc:mysql://localhost:3306/ktor_moashrafff_db"
  driver: "com.mysql.cj.jdbc.Driver"
  user: "ktor_moashrafff_db_user"

