ktor:
    application:
        modules:
            - com.moashraf.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

databse:
  url: "jdbc:mysql://localhost:3306/ktor_moashrafff_db"
  driver: "com.mysql.cj.jdbc.Driver"
  user: "mo"

